- hosts: localhost
  vars:
    - github_token: "TOKEN HERE"
    - ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Create a GitHub Repo
      github_repo:
        github_auth_key:  "{{github_token}}" 
        username: "jerryleeadams"
        name: "Hello-World"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      tags:
      - never
      - createrepo
      register: result
    - name: Delete GitHub Repo
      github_repo:
        github_auth_key:  "{{github_token}}" 
        username: "jerryleeadams"
        name: "Hello-World"
        state: absent
      tags:
      - never
      - deleterepo

    - debug: var=result